# Generated by Django 5.0 on 2024-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.IntegerField(),
        ),
    ]
